In [0]:
import numpy as np

In [0]:
x1 = [0.18, 1.0, 0.92, 0.07, 0.85, 0.99, 0.87]
x2 = [0.89, 0.26, 0.11, 0.37, 0.16, 0.41, 0.47]
y = [109.85, 155.72, 137.66, 76.17, 139.75, 162.6, 151.77]

In [0]:
X = np.array([x1, x2])
X = X.transpose()
y = np.array(y)
y = y.reshape(y.shape[0], 1)

In [0]:
def cost(w, b, X, y):
  y_pred = np.dot(X, w) + b
  error = y - y_pred
  error = np.power(error, 2)
  return sum(error) / len(y)

In [0]:
def gradW(w, b, X, y):
  y_pred = np.dot(X, w) + b
  error = y - y_pred
  error = np.transpose(error)
  return  ((-2 * np.dot(error, X)) / len(y)).transpose();

In [0]:
def gradb(w, b, X, y):
  y_pred = np.dot(X, w) + b
  error = y - y_pred
  error = sum(error)
  return  -2 * error / len(y)

In [0]:
costTest = []

In [0]:
w = np.random.normal(size = (2, 1))
b = np.random.normal(size = (1, 1))

In [0]:
for i in range(0, 30):
  
  newCost = cost(w, b, X, y)
  costTest.append(newCost)
  w = w - (0.5 * gradW(w, b, X, y))
  b = b - (0.5 * gradb(w, b, X, y))

In [0]:
costTest

[array([18337.36325216]),
 array([16.70601656]),
 array([13.23752588]),
 array([10.76282485]),
 array([8.99020061]),
 array([7.71401637]),
 array([6.78928479]),
 array([6.11375398]),
 array([5.61528646]),
 array([5.24296703]),
 array([4.96083766]),
 array([4.74348336]),
 array([4.57292198]),
 array([4.43641269]),
 array([4.32491176]),
 array([4.23198434]),
 array([4.15303748]),
 array([4.08477965]),
 array([4.02483962]),
 array([3.97149777]),
 array([3.92349664]),
 array([3.87990722]),
 array([3.84003456]),
 array([3.80335117]),
 array([3.76944986]),
 array([3.73801043]),
 array([3.70877603]),
 array([3.6815364]),
 array([3.65611591]),
 array([3.63236506])]